### ISSUE TITLE
SIGABRT - patch function

### ISSUE THREAD

**Issue by mytuzmen** [sat-p/Exempler-Inpainting#1]
I am trying to run your implementation on Android with Java Native Interface. When I try to run your code with my image and mask, I am getting a SIGABRT error in the patch function when radius becomes negative and cv::Range function gives an error. 

My mask image is not a rectangular field, it is a random mask. Could it be the reason? 

Do you have any idea about what could be wrong? Thank you.

**Comment by sat-p** [comment]
The mask does not need to be a rectangular field.

@mytuzmen , Is the size of the bitmap which you're using as the mask (set by calling the mask() function) the same as the size of the image to be inpainted?

**Comment by mytuzmen** [comment]
![mask_test](https://user-images.githubusercontent.com/24810759/51671890-66333e80-1fca-11e9-9bd1-224fe1be5ea2.jpg)
![input_test](https://user-images.githubusercontent.com/24810759/51671891-66333e80-1fca-11e9-9081-836fe0b27d7d.jpg)

These are the input and mask images that I am using for testing. I tried negating the mask image, however, it did not work either. 

What could be wrong? Thank you.

**Comment by sat-p** [comment]
Sorry I couldn't help you then. I suppose I was preoccupied with something back then.
